sudo: required
services:
  - docker

before_install:
  - docker build -t luisgerrarrdo/docker-react -f Dockerfile.dev .

script:
  - docker run luisgerrarrdo/docker-react npm run test -- --coverage
  